import React from 'react';
import { useSimStore } from '../store/useSimStore';
import { MonitorPlay, Users, TrendingUp } from 'lucide-react';

export default function AcquisitionControls() {
  const store = useSimStore();

  const handleSlider = (key, val) => {
    store.setLever(key, Number(val));
  };

  const formatNum = (val) => new Intl.NumberFormat('en-US').format(val);

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl shadow-xl overflow-hidden font-sans">
      
      {/* Header */}
      <div className="bg-slate-950/50 p-4 border-b border-slate-800 flex items-center justify-between">
        <h2 className="text-sm font-black uppercase tracking-widest text-indigo-400 flex items-center gap-2">
          <MonitorPlay size={16}/> Traffic Funnel
        </h2>
      </div>

      <div className="p-5 space-y-6">
        
        {/* Top of Funnel (Views) */}
        <div>
          <div className="flex justify-between text-xs font-semibold mb-1">
            <span className="text-slate-300 flex items-center gap-1.5"><Users size={12}/> Monthly Active Views</span>
            <span className="text-indigo-400">{formatNum(store.creatorViews)}</span>
          </div>
          <input 
            type="range" min="10000" max="1000000" step="10000" 
            value={store.creatorViews} 
            onChange={(e) => handleSlider('creatorViews', e.target.value)} 
            className="w-full accent-indigo-500 h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer" 
          />
          <p className="text-[10px] text-slate-500 mt-1 leading-tight">Total video impressions generated by partnered creators.</p>
        </div>

        {/* Conversion Rate */}
        <div>
          <div className="flex justify-between text-xs font-semibold mb-1">
            <span className="text-slate-300">Viewer Conversion Rate</span>
            <span className="text-indigo-400">{store.viewerConversion.toFixed(1)}%</span>
          </div>
          <input 
            type="range" min="0.1" max="5.0" step="0.1" 
            value={store.viewerConversion} 
            onChange={(e) => handleSlider('viewerConversion', e.target.value)} 
            className="w-full accent-indigo-500 h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer" 
          />
          <p className="text-[10px] text-slate-500 mt-1 leading-tight">% of viewers who authenticate and join the server network.</p>
        </div>

        {/* Creator Rev Share (The Engine) */}
        <div className="pt-4 border-t border-slate-800">
          <div className="flex justify-between text-xs font-semibold mb-1">
            <span className="text-slate-300 flex items-center gap-1.5"><TrendingUp size={12}/> Creator Rev Share Payout</span>
            <span className="text-rose-400">{store.creatorShare}%</span>
          </div>
          <input 
            type="range" min="10" max="50" step="1" 
            value={store.creatorShare} 
            onChange={(e) => handleSlider('creatorShare', e.target.value)} 
            className="w-full accent-rose-500 h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer" 
          />
          <div className="mt-2 bg-rose-950/20 border border-rose-900/30 p-2 rounded">
            <p className="text-[10px] text-rose-300/80 leading-tight">
              <strong>Economic Impact:</strong> At {store.creatorShare}%, creators are motivated to operate at <span className="text-rose-400 font-bold">{Math.round((Math.max(0.65, 0.75 + (store.creatorShare - 15) * 0.012)) * 100)}%</span> of maximum promotional capacity. Higher payouts reduce viewer fatigue.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
}